// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwFb_xB4aq2jkjH2A_bdr9RoGAWD8LZb4',
    appId: '1:566433648370:android:6b3a4b00236f2f11eb4a6b',
    messagingSenderId: '566433648370',
    projectId: 'washamproject',
    storageBucket: 'washamproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTcFIeWvX4hIw6UURdjl2I2ktb9O5EVw8',
    appId: '1:566433648370:ios:4120d53b7f0d19b2eb4a6b',
    messagingSenderId: '566433648370',
    projectId: 'washamproject',
    storageBucket: 'washamproject.firebasestorage.app',
    iosClientId: '566433648370-6k7vcvn23pu1aj7kbspflapi0ai6l44s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterwasham',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhAWcRh0a8Ie6tHazJmEhlJNOXl1A-Ey0',
    appId: '1:566433648370:web:1cec109f5d527e77eb4a6b',
    messagingSenderId: '566433648370',
    projectId: 'washamproject',
    authDomain: 'washamproject.firebaseapp.com',
    storageBucket: 'washamproject.firebasestorage.app',
    measurementId: 'G-RQK2NGT9CH',
  );

}